//! Wireshark Lua dissector generator.
//!
//! Produces a self-contained `.lua` script that registers a Wireshark
//! protocol dissector for UDP traffic.  The dissector decodes packets by
//! matching them against the leaf containers found in the XTCE document.
//!
//! # Dispatch strategy
//!
//! If every leaf container has a single-parameter equality discriminator
//! (e.g. all share an `APID` field with a distinct required value), the
//! generated dissector builds a dispatch table keyed on that value and calls
//! the appropriate per-container `dissect_<Name>` function.  Otherwise it
//! emits all fields of all containers without dispatch (useful for simple
//! single-packet-type documents).
//!
//! # Limitations
//!
//! - Only `ParameterRef` entries are decoded; `ContainerRef` and `FixedValue`
//!   padding fields are skipped in the output (but their offsets are tracked).
//! - Aggregate and Array parameter types are emitted as `Unknown` fields.

use crate::layout::{FieldLayout, LeafContainer, TypeInfo};
use xtce_core::model::types::ValueEnumeration;

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point
// ─────────────────────────────────────────────────────────────────────────────

/// Generate a complete Wireshark Lua dissector for the given leaf containers.
///
/// The dissector listens on UDP `port`.  If all containers share a common
/// single-parameter equality discriminator (e.g. an APID field), the
/// dissector dispatches by that value.  Otherwise it shows all fields of all
/// containers without dispatch.
pub fn generate_lua(leaves: &[LeafContainer], port: u16) -> String {
    let mut out = String::with_capacity(4096);

    out.push_str("-- Auto-generated XTCE Wireshark Lua dissector\n");
    out.push_str("-- Generated by xtce-tools gen-dissector\n\n");

    out.push_str("local xtce_proto = Proto(\"xtce\", \"XTCE Telemetry\")\n\n");

    // ── ProtoField declarations ─────────────────────────────────────────────
    out.push_str("-- ProtoField declarations\n");
    out.push_str("local F = {}\n");
    for lc in leaves {
        let prefix = lua_id(&lc.name);
        for field in &lc.fields {
            if field.name.starts_with("_pad_") {
                continue;
            }
            let key = format!("{}.{}", prefix, lua_id(&field.name));
            let abbrev = format!("xtce.{}.{}", prefix, lua_id(&field.name));
            let label = &field.name;
            let proto_field = proto_field_call(&abbrev, label, &field.type_info);
            out.push_str(&format!("F[\"{key}\"] = {proto_field}\n"));
        }
    }
    out.push('\n');

    // Register all fields with the proto.
    out.push_str("local _all_fields = {}\n");
    out.push_str("for _, f in pairs(F) do _all_fields[#_all_fields+1] = f end\n");
    out.push_str("xtce_proto.fields = _all_fields\n\n");

    // ── Per-container dissect functions ────────────────────────────────────
    for lc in leaves {
        emit_container_function(&mut out, lc);
    }

    // ── Discriminator map (if applicable) ──────────────────────────────────
    let discriminator_param = detect_common_discriminator(leaves);

    if let Some(param_name) = &discriminator_param {
        out.push_str("-- Discriminator dispatch map\n");
        out.push_str("local XTCE_MAP = {\n");
        for lc in leaves {
            if let Some(d) = &lc.discriminator {
                out.push_str(&format!(
                    "    [{}] = dissect_{},\n",
                    d.value,
                    lua_id(&lc.name)
                ));
            }
        }
        out.push_str("}\n\n");

        // Determine bit offset and size of the discriminator field in a base
        // container that is common to all leaves (best effort: use the first
        // leaf's field list to locate the parameter).
        let (disc_bit_offset, disc_size_bits, disc_lsb) =
            find_field_location(leaves, param_name);
        let min_len = (disc_bit_offset + disc_size_bits + 7) / 8;

        out.push_str("-- Main dissect function\n");
        out.push_str("function xtce_proto.dissector(buf, pkt, tree)\n");
        out.push_str("    pkt.cols.protocol = \"XTCE\"\n");
        out.push_str("    local subtree = tree:add(xtce_proto, buf(), \"XTCE Telemetry\")\n");
        out.push_str(&format!("    if buf:len() < {min_len} then return end\n"));

        // Emit the discriminator read, handling byte-aligned vs bit-packed.
        if disc_bit_offset % 8 == 0 && disc_size_bits % 8 == 0 {
            let byte_off = disc_bit_offset / 8;
            let byte_len = disc_size_bits / 8;
            let uint_fn = if disc_lsb { "le_uint" } else { "uint" };
            out.push_str(&format!(
                "    local disc_val = buf({byte_off}, {byte_len}):{uint_fn}()\n"
            ));
        } else {
            // Unaligned discriminator — use bitfield() (always big-endian bit order).
            let byte_off = disc_bit_offset / 8;
            let bit_in_byte = disc_bit_offset % 8;
            let byte_span = (bit_in_byte + disc_size_bits + 7) / 8;
            out.push_str(&format!(
                "    local disc_val = buf({byte_off}, {byte_span}):bitfield({bit_in_byte}, {disc_size_bits})\n"
            ));
        }

        out.push_str("    local fn = XTCE_MAP[disc_val]\n");
        out.push_str("    if fn then fn(buf, pkt, subtree)\n");
        out.push_str("    else subtree:add(\"Unknown packet type: \" .. disc_val) end\n");

        // Containers without a discriminator are always decoded (e.g. shared headers).
        let undiscriminated: Vec<_> =
            leaves.iter().filter(|l| l.discriminator.is_none()).collect();
        if !undiscriminated.is_empty() {
            out.push_str("    -- Undiscriminated containers (always decoded)\n");
            for lc in &undiscriminated {
                out.push_str(&format!(
                    "    dissect_{}(buf, pkt, subtree)\n",
                    lua_id(&lc.name)
                ));
            }
        }

        out.push_str("end\n\n");
    } else {
        // No discriminator — just show the first container's fields (or all).
        out.push_str("-- No common discriminator found; showing all containers\n");
        out.push_str("function xtce_proto.dissector(buf, pkt, tree)\n");
        out.push_str("    pkt.cols.protocol = \"XTCE\"\n");
        out.push_str("    local subtree = tree:add(xtce_proto, buf(), \"XTCE Telemetry\")\n");
        for lc in leaves {
            out.push_str(&format!(
                "    dissect_{}(buf, pkt, subtree)\n",
                lua_id(&lc.name)
            ));
        }
        out.push_str("end\n\n");
    }

    // ── UDP registration ────────────────────────────────────────────────────
    out.push_str(&format!("local PORT = {port}\n"));
    out.push_str("local udp_table = DissectorTable.get(\"udp.port\")\n");
    out.push_str("udp_table:add(PORT, xtce_proto)\n");

    out
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Sanitise a name for use as a Lua identifier component.
pub fn lua_id(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>()
        .to_lowercase()
}

/// Return the `ProtoField.<type>(...)` call for a given field.
fn proto_field_call(abbrev: &str, label: &str, ti: &TypeInfo) -> String {
    match ti {
        TypeInfo::Integer { signed, size_in_bits, .. } => {
            let (pf_type, base) = match (signed, size_in_bits) {
                (false, 8) => ("uint8", "base.DEC"),
                (false, 16) => ("uint16", "base.DEC"),
                (false, 32) => ("uint32", "base.DEC"),
                (false, 64) => ("uint64", "base.DEC"),
                (true, 8) => ("int8", "base.DEC"),
                (true, 16) => ("int16", "base.DEC"),
                (true, 32) => ("int32", "base.DEC"),
                (true, 64) => ("int64", "base.DEC"),
                (false, _) => ("uint32", "base.DEC"),
                (true, _) => ("int32", "base.DEC"),
            };
            format!("ProtoField.{pf_type}(\"{abbrev}\", \"{label}\", {base})")
        }
        TypeInfo::Float { size_in_bits, .. } => {
            let pf = if *size_in_bits == 64 { "double" } else { "float" };
            format!("ProtoField.{pf}(\"{abbrev}\", \"{label}\")")
        }
        TypeInfo::Enum { size_in_bits, values } => {
            let table = build_enum_table(values);
            let pf = if *size_in_bits <= 8 {
                "uint8"
            } else if *size_in_bits <= 16 {
                "uint16"
            } else {
                "uint32"
            };
            format!("ProtoField.{pf}(\"{abbrev}\", \"{label}\", base.DEC, {table})")
        }
        TypeInfo::Boolean { .. } => {
            format!("ProtoField.bool(\"{abbrev}\", \"{label}\")")
        }
        TypeInfo::StringField { .. } => {
            format!("ProtoField.string(\"{abbrev}\", \"{label}\")")
        }
        TypeInfo::Binary { .. } | TypeInfo::Unknown { .. } => {
            format!("ProtoField.bytes(\"{abbrev}\", \"{label}\")")
        }
    }
}

fn build_enum_table(values: &[ValueEnumeration]) -> String {
    let mut t = String::from("{");
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            t.push_str(", ");
        }
        let label = v.label.replace('"', "'");
        t.push_str(&format!("[{}]=\"{}\"", v.value, label));
    }
    t.push('}');
    t
}

/// Emit a `local function dissect_<name>(buf, pkt, tree) ... end` block.
fn emit_container_function(out: &mut String, lc: &LeafContainer) {
    let fn_name = lua_id(&lc.name);
    out.push_str(&format!(
        "-- Container: {} ({})\n",
        lc.name, lc.full_path
    ));
    out.push_str(&format!(
        "local function dissect_{fn_name}(buf, pkt, tree)\n"
    ));

    for field in &lc.fields {
        if field.name.starts_with("_pad_") {
            continue;
        }
        emit_field_add(out, &fn_name, field);
    }

    out.push_str("end\n\n");
}

/// Return true if a `TypeInfo` is little-endian (LSB-first byte order).
fn is_lsb(ti: &TypeInfo) -> bool {
    matches!(
        ti,
        TypeInfo::Integer { byte_order_lsb: true, .. }
            | TypeInfo::Float { byte_order_lsb: true, .. }
    )
}

/// Emit one `tree:add(...)` line for a field.
///
/// Byte-aligned fields use `tree:add` (big-endian) or `tree:add_le`
/// (little-endian).  Unaligned fields always use `buf():bitfield()`, which
/// reads bits in big-endian order — little-endian bit-packed fields are not
/// supported by Wireshark's Lua API and are emitted as big-endian with a
/// comment warning.
fn emit_field_add(out: &mut String, container_id: &str, field: &FieldLayout) {
    let key = format!("{}.{}", container_id, lua_id(&field.name));
    let size = field.type_info.size_in_bits();
    let bit_off = field.bit_offset;
    let lsb = is_lsb(&field.type_info);

    if bit_off % 8 == 0 && size % 8 == 0 {
        // Byte-aligned — simple slice with correct endian method.
        let byte_off = bit_off / 8;
        let byte_len = size / 8;
        let add_fn = if lsb { "add_le" } else { "add" };
        out.push_str(&format!(
            "    if buf:len() >= {} then tree:{add_fn}(F[\"{key}\"], buf({byte_off}, {byte_len})) end\n",
            byte_off + byte_len
        ));
    } else {
        // Sub-byte or unaligned — use bitfield() (big-endian bit order only).
        let byte_off = bit_off / 8;
        let bit_in_byte = bit_off % 8;
        let byte_span = ((bit_in_byte + size) + 7) / 8;
        if lsb {
            out.push_str(&format!(
                "    -- WARNING: {key} is little-endian but unaligned; decoded as big-endian\n"
            ));
        }
        out.push_str(&format!(
            "    if buf:len() >= {} then tree:add(F[\"{key}\"], buf({byte_off}, {byte_span}):bitfield({bit_in_byte}, {size})) end\n",
            byte_off + byte_span
        ));
    }
}

/// If all leaf containers with discriminators share the same parameter name,
/// return that name.
fn detect_common_discriminator(leaves: &[LeafContainer]) -> Option<String> {
    let discriminated: Vec<_> = leaves.iter().filter(|l| l.discriminator.is_some()).collect();
    if discriminated.is_empty() {
        return None;
    }
    let first = discriminated[0].discriminator.as_ref().unwrap().param_name.clone();
    if discriminated
        .iter()
        .all(|l| l.discriminator.as_ref().unwrap().param_name == first)
    {
        Some(first)
    } else {
        None
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layout::{DiscriminatorInfo, FieldLayout, LeafContainer, TypeInfo};

    // ── Helpers ───────────────────────────────────────────────────────────────

    fn make_leaf(
        name: &str,
        discriminator: Option<DiscriminatorInfo>,
        fields: Vec<FieldLayout>,
    ) -> LeafContainer {
        let total_bits = fields
            .iter()
            .map(|f| f.bit_offset + f.type_info.size_in_bits())
            .max()
            .unwrap_or(0);
        LeafContainer {
            name: name.to_string(),
            full_path: format!("Root/{name}"),
            discriminator,
            fields,
            total_bits,
        }
    }

    fn make_disc(param_name: &str, value: i64) -> DiscriminatorInfo {
        DiscriminatorInfo { param_name: param_name.to_string(), value }
    }

    fn uint_field(name: &str, bit_offset: u32, size: u32, lsb: bool) -> FieldLayout {
        FieldLayout {
            name: name.to_string(),
            type_info: TypeInfo::Integer {
                signed: false,
                size_in_bits: size,
                byte_order_lsb: lsb,
            },
            bit_offset,
        }
    }

    fn unaligned_field(name: &str, bit_offset: u32, size: u32, lsb: bool) -> FieldLayout {
        // size chosen so (bit_offset % 8 != 0) || (size % 8 != 0) holds
        FieldLayout {
            name: name.to_string(),
            type_info: TypeInfo::Integer {
                signed: false,
                size_in_bits: size,
                byte_order_lsb: lsb,
            },
            bit_offset,
        }
    }

    // ── Task 3: discriminator dispatch ────────────────────────────────────────

    /// All leaves share a discriminator → XTCE_MAP emitted, no unconditional calls.
    #[test]
    fn test_all_discriminated_emits_map_only() {
        let disc = uint_field("APID", 0, 16, false);
        let leaves = vec![
            make_leaf("PktA", Some(make_disc("APID", 100)), vec![disc.clone()]),
            make_leaf("PktB", Some(make_disc("APID", 200)), vec![disc.clone()]),
        ];
        let lua = generate_lua(&leaves, 4321);

        assert!(lua.contains("XTCE_MAP"), "dispatch map should be present");
        assert!(lua.contains("[100] = dissect_pkta"), "APID 100 → PktA");
        assert!(lua.contains("[200] = dissect_pktb"), "APID 200 → PktB");
        assert!(!lua.contains("Undiscriminated"),
            "no undiscriminated section when all leaves have a discriminator");
    }

    /// Mixed leaves: one discriminated, one not → XTCE_MAP + unconditional call.
    #[test]
    fn test_mixed_leaves_emits_map_and_unconditional() {
        let disc = uint_field("APID", 0, 16, false);
        let leaves = vec![
            make_leaf("PktA", Some(make_disc("APID", 100)), vec![disc.clone()]),
            make_leaf("Common", None, vec![uint_field("Status", 0, 8, false)]),
        ];
        let lua = generate_lua(&leaves, 4321);

        assert!(lua.contains("XTCE_MAP"), "dispatch map should be present");
        assert!(lua.contains("[100] = dissect_pkta"), "APID 100 → PktA");
        assert!(lua.contains("Undiscriminated"),
            "undiscriminated section should be present");
        assert!(lua.contains("dissect_common(buf, pkt, subtree)"),
            "Common should be called unconditionally");
        // Common must NOT be in the XTCE_MAP
        assert!(!lua.contains("dissect_common,"),
            "Common must not appear in XTCE_MAP");
    }

    /// No discriminators at all → fallback path calls every dissect function.
    #[test]
    fn test_no_discriminator_calls_all() {
        let leaves = vec![
            make_leaf("PktA", None, vec![uint_field("A", 0, 8, false)]),
            make_leaf("PktB", None, vec![uint_field("B", 0, 8, false)]),
        ];
        let lua = generate_lua(&leaves, 4321);

        assert!(!lua.contains("XTCE_MAP"), "no dispatch map without discriminators");
        assert!(lua.contains("dissect_pkta(buf, pkt, subtree)"));
        assert!(lua.contains("dissect_pktb(buf, pkt, subtree)"));
    }

    // ── Task 4: byte order and alignment ──────────────────────────────────────

    /// Byte-aligned little-endian field → tree:add_le.
    #[test]
    fn test_le_field_uses_add_le() {
        let leaves = vec![make_leaf("Pkt", None, vec![uint_field("Val", 0, 16, true)])];
        let lua = generate_lua(&leaves, 4321);
        assert!(lua.contains("tree:add_le(F[\"pkt.val\"]"),
            "LE byte-aligned field must use add_le");
    }

    /// Byte-aligned big-endian field → tree:add (not add_le).
    #[test]
    fn test_be_field_uses_add() {
        let leaves = vec![make_leaf("Pkt", None, vec![uint_field("Val", 0, 16, false)])];
        let lua = generate_lua(&leaves, 4321);
        assert!(lua.contains("tree:add(F[\"pkt.val\"]"),
            "BE byte-aligned field must use add");
        assert!(!lua.contains("add_le"),
            "BE field must not use add_le");
    }

    /// Non-byte-aligned field → buf():bitfield().
    #[test]
    fn test_unaligned_field_uses_bitfield() {
        // bit_offset=5, size=3 → neither byte-aligned nor byte-sized
        let leaves = vec![make_leaf("Pkt", None, vec![unaligned_field("Val", 5, 3, false)])];
        let lua = generate_lua(&leaves, 4321);
        assert!(lua.contains(":bitfield("),
            "unaligned field must use bitfield");
    }

    /// Unaligned little-endian field → WARNING comment + bitfield fallback.
    #[test]
    fn test_unaligned_le_field_emits_warning_and_bitfield() {
        let leaves = vec![make_leaf("Pkt", None, vec![unaligned_field("Val", 5, 3, true)])];
        let lua = generate_lua(&leaves, 4321);
        assert!(lua.contains("WARNING"),
            "unaligned LE field must emit a WARNING comment");
        assert!(lua.contains(":bitfield("),
            "unaligned LE field must still use bitfield");
        assert!(!lua.contains("add_le"),
            "unaligned LE field must NOT use add_le (not supported by Wireshark)");
    }

    /// LE discriminator → le_uint() read in main dissector.
    #[test]
    fn test_le_discriminator_uses_le_uint() {
        let disc = uint_field("APID", 0, 16, true); // LE
        let leaves = vec![
            make_leaf("PktA", Some(make_disc("APID", 100)), vec![disc.clone()]),
            make_leaf("PktB", Some(make_disc("APID", 200)), vec![disc.clone()]),
        ];
        let lua = generate_lua(&leaves, 4321);
        assert!(lua.contains(":le_uint()"),
            "LE discriminator field must use le_uint()");
        assert!(!lua.contains(":uint()"),
            "LE discriminator must not use uint()");
    }

    /// Bit-unaligned discriminator → bitfield() read in main dissector.
    #[test]
    fn test_unaligned_discriminator_uses_bitfield() {
        // bit_offset=5, size=3 — not byte-aligned
        let disc = unaligned_field("TypeId", 5, 3, false);
        let leaves = vec![
            make_leaf("PktA", Some(make_disc("TypeId", 1)), vec![disc.clone()]),
            make_leaf("PktB", Some(make_disc("TypeId", 2)), vec![disc.clone()]),
        ];
        let lua = generate_lua(&leaves, 4321);
        assert!(lua.contains(":bitfield("),
            "unaligned discriminator must use bitfield()");
        assert!(!lua.contains(":uint()"),
            "unaligned discriminator must not use uint()");
    }
}

/// Find the bit offset, bit size, and byte-order of `param_name` in the first
/// leaf that contains it.  Returns `(bit_offset, size_in_bits, is_lsb)`.
/// Falls back to `(0, 16, false)` if the field is not found.
fn find_field_location(leaves: &[LeafContainer], param_name: &str) -> (u32, u32, bool) {
    for lc in leaves {
        if let Some(f) = lc.fields.iter().find(|f| f.name == param_name) {
            let is_lsb = matches!(
                &f.type_info,
                TypeInfo::Integer { byte_order_lsb: true, .. }
                    | TypeInfo::Float { byte_order_lsb: true, .. }
            );
            return (f.bit_offset, f.type_info.size_in_bits(), is_lsb);
        }
    }
    (0, 16, false)
}
