-- Auto-generated XTCE Wireshark Lua dissector
-- Generated by xtce-tools gen-dissector

local xtce_proto = Proto("xtce", "XTCE Telemetry")

-- ProtoField declarations
local F = {}
F["adcspacket.versionnumber"] = ProtoField.uint8("xtce.adcspacket.versionnumber", "VersionNumber", base.DEC)
F["adcspacket.packettype"] = ProtoField.uint8("xtce.adcspacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["adcspacket.sechdrflag"] = ProtoField.bool("xtce.adcspacket.sechdrflag", "SecHdrFlag")
F["adcspacket.apid"] = ProtoField.uint16("xtce.adcspacket.apid", "APID", base.DEC)
F["adcspacket.seqflags"] = ProtoField.uint8("xtce.adcspacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["adcspacket.seqcount"] = ProtoField.uint16("xtce.adcspacket.seqcount", "SeqCount", base.DEC)
F["adcspacket.datalength"] = ProtoField.uint16("xtce.adcspacket.datalength", "DataLength", base.DEC)
F["adcspacket.q0"] = ProtoField.float("xtce.adcspacket.q0", "Q0")
F["adcspacket.q1"] = ProtoField.float("xtce.adcspacket.q1", "Q1")
F["adcspacket.q2"] = ProtoField.float("xtce.adcspacket.q2", "Q2")
F["adcspacket.q3"] = ProtoField.float("xtce.adcspacket.q3", "Q3")
F["adcspacket.omegax"] = ProtoField.float("xtce.adcspacket.omegax", "OmegaX")
F["adcspacket.omegay"] = ProtoField.float("xtce.adcspacket.omegay", "OmegaY")
F["adcspacket.omegaz"] = ProtoField.float("xtce.adcspacket.omegaz", "OmegaZ")
F["adcspacket.sunangle"] = ProtoField.float("xtce.adcspacket.sunangle", "SunAngle")
F["adcspacket.adcsmode"] = ProtoField.uint8("xtce.adcspacket.adcsmode", "ADCSMode", base.DEC, {[0]="STANDBY", [1]="NOMINAL", [2]="SCIENCE", [3]="ECLIPSE", [4]="SAFE", [5]="CONTINGENCY"})
F["adcspacket.stvalid"] = ProtoField.bool("xtce.adcspacket.stvalid", "STValid")
F["adcspacket.starcount"] = ProtoField.uint8("xtce.adcspacket.starcount", "StarCount", base.DEC)
F["commpacket.versionnumber"] = ProtoField.uint8("xtce.commpacket.versionnumber", "VersionNumber", base.DEC)
F["commpacket.packettype"] = ProtoField.uint8("xtce.commpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["commpacket.sechdrflag"] = ProtoField.bool("xtce.commpacket.sechdrflag", "SecHdrFlag")
F["commpacket.apid"] = ProtoField.uint16("xtce.commpacket.apid", "APID", base.DEC)
F["commpacket.seqflags"] = ProtoField.uint8("xtce.commpacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["commpacket.seqcount"] = ProtoField.uint16("xtce.commpacket.seqcount", "SeqCount", base.DEC)
F["commpacket.datalength"] = ProtoField.uint16("xtce.commpacket.datalength", "DataLength", base.DEC)
F["commpacket.txpower"] = ProtoField.int8("xtce.commpacket.txpower", "TxPower", base.DEC)
F["commpacket.rxsignal"] = ProtoField.int8("xtce.commpacket.rxsignal", "RxSignal", base.DEC)
F["commpacket.framessent"] = ProtoField.uint32("xtce.commpacket.framessent", "FramesSent", base.DEC)
F["commpacket.framesreceived"] = ProtoField.uint32("xtce.commpacket.framesreceived", "FramesReceived", base.DEC)
F["commpacket.frameserrored"] = ProtoField.uint16("xtce.commpacket.frameserrored", "FramesErrored", base.DEC)
F["commpacket.linkstate"] = ProtoField.uint8("xtce.commpacket.linkstate", "LinkState", base.DEC, {[0]="IDLE", [1]="ACQUISITION", [2]="TRACKING", [3]="LOCKED", [4]="LOST"})
F["commpacket.symbolrate"] = ProtoField.uint32("xtce.commpacket.symbolrate", "SymbolRate", base.DEC)
F["eventpacket.versionnumber"] = ProtoField.uint8("xtce.eventpacket.versionnumber", "VersionNumber", base.DEC)
F["eventpacket.packettype"] = ProtoField.uint8("xtce.eventpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["eventpacket.sechdrflag"] = ProtoField.bool("xtce.eventpacket.sechdrflag", "SecHdrFlag")
F["eventpacket.apid"] = ProtoField.uint16("xtce.eventpacket.apid", "APID", base.DEC)
F["eventpacket.seqflags"] = ProtoField.uint8("xtce.eventpacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["eventpacket.seqcount"] = ProtoField.uint16("xtce.eventpacket.seqcount", "SeqCount", base.DEC)
F["eventpacket.datalength"] = ProtoField.uint16("xtce.eventpacket.datalength", "DataLength", base.DEC)
F["eventpacket.eventtimestamp"] = ProtoField.bytes("xtce.eventpacket.eventtimestamp", "EventTimestamp")
F["eventpacket.eventid"] = ProtoField.uint16("xtce.eventpacket.eventid", "EventId", base.DEC)
F["eventpacket.eventseverity"] = ProtoField.uint8("xtce.eventpacket.eventseverity", "EventSeverity", base.DEC, {[0]="DEBUG", [1]="INFO", [2]="WARNING", [3]="ERROR", [4]="CRITICAL"})
F["eventpacket.eventsubsystem"] = ProtoField.uint8("xtce.eventpacket.eventsubsystem", "EventSubsystem", base.DEC, {[0]="OBC", [1]="ADCS", [2]="POWER", [3]="COMMS", [4]="PAYLOAD", [5]="THERMAL"})
F["eventpacket.eventrepeatcount"] = ProtoField.uint8("xtce.eventpacket.eventrepeatcount", "EventRepeatCount", base.DEC)
F["eventpacket.eventsuppressed"] = ProtoField.bool("xtce.eventpacket.eventsuppressed", "EventSuppressed")
F["eventpacket.eventmessage"] = ProtoField.string("xtce.eventpacket.eventmessage", "EventMessage")
F["hkpacket.versionnumber"] = ProtoField.uint8("xtce.hkpacket.versionnumber", "VersionNumber", base.DEC)
F["hkpacket.packettype"] = ProtoField.uint8("xtce.hkpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["hkpacket.sechdrflag"] = ProtoField.bool("xtce.hkpacket.sechdrflag", "SecHdrFlag")
F["hkpacket.apid"] = ProtoField.uint16("xtce.hkpacket.apid", "APID", base.DEC)
F["hkpacket.seqflags"] = ProtoField.uint8("xtce.hkpacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["hkpacket.seqcount"] = ProtoField.uint16("xtce.hkpacket.seqcount", "SeqCount", base.DEC)
F["hkpacket.datalength"] = ProtoField.uint16("xtce.hkpacket.datalength", "DataLength", base.DEC)
F["hkpacket.scmode"] = ProtoField.uint8("xtce.hkpacket.scmode", "SCMode", base.DEC, {[0]="STANDBY", [1]="NOMINAL", [2]="SCIENCE", [3]="ECLIPSE", [4]="SAFE", [5]="CONTINGENCY"})
F["hkpacket.met"] = ProtoField.bytes("xtce.hkpacket.met", "MET")
F["hkpacket.resetcause"] = ProtoField.uint8("xtce.hkpacket.resetcause", "ResetCause", base.DEC, {[0]="POR", [1]="WDT", [2]="CMD", [3]="FAULT", [4]="UNKNOWN"})
F["hkpacket.resetcount"] = ProtoField.uint16("xtce.hkpacket.resetcount", "ResetCount", base.DEC)
F["hkpacket.eclipseflag"] = ProtoField.bool("xtce.hkpacket.eclipseflag", "EclipseFlag")
F["hkpacket.safemodeflag"] = ProtoField.bool("xtce.hkpacket.safemodeflag", "SafeModeFlag")
F["hkpacket.battsoc"] = ProtoField.uint8("xtce.hkpacket.battsoc", "BattSOC", base.DEC)
F["obcpacket.versionnumber"] = ProtoField.uint8("xtce.obcpacket.versionnumber", "VersionNumber", base.DEC)
F["obcpacket.packettype"] = ProtoField.uint8("xtce.obcpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["obcpacket.sechdrflag"] = ProtoField.bool("xtce.obcpacket.sechdrflag", "SecHdrFlag")
F["obcpacket.apid"] = ProtoField.uint16("xtce.obcpacket.apid", "APID", base.DEC)
F["obcpacket.seqflags"] = ProtoField.uint8("xtce.obcpacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["obcpacket.seqcount"] = ProtoField.uint16("xtce.obcpacket.seqcount", "SeqCount", base.DEC)
F["obcpacket.datalength"] = ProtoField.uint16("xtce.obcpacket.datalength", "DataLength", base.DEC)
F["obcpacket.cpuload1s"] = ProtoField.uint8("xtce.obcpacket.cpuload1s", "CPULoad1s", base.DEC)
F["obcpacket.cpuload5s"] = ProtoField.uint8("xtce.obcpacket.cpuload5s", "CPULoad5s", base.DEC)
F["obcpacket.cpuload15s"] = ProtoField.uint8("xtce.obcpacket.cpuload15s", "CPULoad15s", base.DEC)
F["obcpacket.memfreekb"] = ProtoField.uint32("xtce.obcpacket.memfreekb", "MemFreeKB", base.DEC)
F["obcpacket.flasherrors"] = ProtoField.uint16("xtce.obcpacket.flasherrors", "FlashErrors", base.DEC)
F["obcpacket.coretemp"] = ProtoField.uint16("xtce.obcpacket.coretemp", "CoreTemp", base.DEC)
F["calpacket.versionnumber"] = ProtoField.uint8("xtce.calpacket.versionnumber", "VersionNumber", base.DEC)
F["calpacket.packettype"] = ProtoField.uint8("xtce.calpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["calpacket.sechdrflag"] = ProtoField.bool("xtce.calpacket.sechdrflag", "SecHdrFlag")
F["calpacket.apid"] = ProtoField.uint16("xtce.calpacket.apid", "APID", base.DEC)
F["calpacket.seqflags"] = ProtoField.uint8("xtce.calpacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["calpacket.seqcount"] = ProtoField.uint16("xtce.calpacket.seqcount", "SeqCount", base.DEC)
F["calpacket.datalength"] = ProtoField.uint16("xtce.calpacket.datalength", "DataLength", base.DEC)
F["calpacket.calstate"] = ProtoField.bool("xtce.calpacket.calstate", "CalState")
F["calpacket.calprogress"] = ProtoField.uint8("xtce.calpacket.calprogress", "CalProgress", base.DEC)
F["calpacket.caltargetch"] = ProtoField.uint8("xtce.calpacket.caltargetch", "CalTargetCh", base.DEC)
F["calpacket.calreference"] = ProtoField.double("xtce.calpacket.calreference", "CalReference")
F["calpacket.caldark"] = ProtoField.double("xtce.calpacket.caldark", "CalDark")
F["scipacket.versionnumber"] = ProtoField.uint8("xtce.scipacket.versionnumber", "VersionNumber", base.DEC)
F["scipacket.packettype"] = ProtoField.uint8("xtce.scipacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["scipacket.sechdrflag"] = ProtoField.bool("xtce.scipacket.sechdrflag", "SecHdrFlag")
F["scipacket.apid"] = ProtoField.uint16("xtce.scipacket.apid", "APID", base.DEC)
F["scipacket.seqflags"] = ProtoField.uint8("xtce.scipacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["scipacket.seqcount"] = ProtoField.uint16("xtce.scipacket.seqcount", "SeqCount", base.DEC)
F["scipacket.datalength"] = ProtoField.uint16("xtce.scipacket.datalength", "DataLength", base.DEC)
F["scipacket.scitimestamp"] = ProtoField.bytes("xtce.scipacket.scitimestamp", "SciTimestamp")
F["scipacket.integtime"] = ProtoField.uint32("xtce.scipacket.integtime", "IntegTime", base.DEC)
F["scipacket.ch1counts"] = ProtoField.uint32("xtce.scipacket.ch1counts", "Ch1Counts", base.DEC)
F["scipacket.ch2counts"] = ProtoField.uint32("xtce.scipacket.ch2counts", "Ch2Counts", base.DEC)
F["scipacket.ch3counts"] = ProtoField.uint32("xtce.scipacket.ch3counts", "Ch3Counts", base.DEC)
F["scipacket.ch4counts"] = ProtoField.uint32("xtce.scipacket.ch4counts", "Ch4Counts", base.DEC)
F["scipacket.ccdtemp"] = ProtoField.uint16("xtce.scipacket.ccdtemp", "CCDTemp", base.DEC)
F["scipacket.darkcurrent"] = ProtoField.float("xtce.scipacket.darkcurrent", "DarkCurrent")
F["scipacket.scichecksum"] = ProtoField.bytes("xtce.scipacket.scichecksum", "SciChecksum")
F["powerpacket.versionnumber"] = ProtoField.uint8("xtce.powerpacket.versionnumber", "VersionNumber", base.DEC)
F["powerpacket.packettype"] = ProtoField.uint8("xtce.powerpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["powerpacket.sechdrflag"] = ProtoField.bool("xtce.powerpacket.sechdrflag", "SecHdrFlag")
F["powerpacket.apid"] = ProtoField.uint16("xtce.powerpacket.apid", "APID", base.DEC)
F["powerpacket.seqflags"] = ProtoField.uint8("xtce.powerpacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["powerpacket.seqcount"] = ProtoField.uint16("xtce.powerpacket.seqcount", "SeqCount", base.DEC)
F["powerpacket.datalength"] = ProtoField.uint16("xtce.powerpacket.datalength", "DataLength", base.DEC)
F["powerpacket.battvoltage"] = ProtoField.uint16("xtce.powerpacket.battvoltage", "BattVoltage", base.DEC)
F["powerpacket.battcurrent"] = ProtoField.int16("xtce.powerpacket.battcurrent", "BattCurrent", base.DEC)
F["powerpacket.solarvoltage"] = ProtoField.uint16("xtce.powerpacket.solarvoltage", "SolarVoltage", base.DEC)
F["powerpacket.solarcurrent"] = ProtoField.uint16("xtce.powerpacket.solarcurrent", "SolarCurrent", base.DEC)
F["powerpacket.battsoc"] = ProtoField.uint8("xtce.powerpacket.battsoc", "BattSOC", base.DEC)
F["powerpacket.batttemp"] = ProtoField.uint16("xtce.powerpacket.batttemp", "BattTemp", base.DEC)
F["powerpacket.powermode"] = ProtoField.uint8("xtce.powerpacket.powermode", "PowerMode", base.DEC, {[0]="CHARGING", [1]="DISCHARGING", [2]="BALANCED", [3]="FAULT"})
F["powerpacket.loadpower"] = ProtoField.float("xtce.powerpacket.loadpower", "LoadPower")
F["powerpacket.chargepower"] = ProtoField.float("xtce.powerpacket.chargepower", "ChargePower")
F["thermalpacket.versionnumber"] = ProtoField.uint8("xtce.thermalpacket.versionnumber", "VersionNumber", base.DEC)
F["thermalpacket.packettype"] = ProtoField.uint8("xtce.thermalpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["thermalpacket.sechdrflag"] = ProtoField.bool("xtce.thermalpacket.sechdrflag", "SecHdrFlag")
F["thermalpacket.apid"] = ProtoField.uint16("xtce.thermalpacket.apid", "APID", base.DEC)
F["thermalpacket.seqflags"] = ProtoField.uint8("xtce.thermalpacket.seqflags", "SeqFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["thermalpacket.seqcount"] = ProtoField.uint16("xtce.thermalpacket.seqcount", "SeqCount", base.DEC)
F["thermalpacket.datalength"] = ProtoField.uint16("xtce.thermalpacket.datalength", "DataLength", base.DEC)
F["thermalpacket.temppcb"] = ProtoField.uint16("xtce.thermalpacket.temppcb", "TempPCB", base.DEC)
F["thermalpacket.tempbattery"] = ProtoField.uint16("xtce.thermalpacket.tempbattery", "TempBattery", base.DEC)
F["thermalpacket.tempsolararray1"] = ProtoField.uint16("xtce.thermalpacket.tempsolararray1", "TempSolarArray1", base.DEC)
F["thermalpacket.tempsolararray2"] = ProtoField.uint16("xtce.thermalpacket.tempsolararray2", "TempSolarArray2", base.DEC)
F["thermalpacket.heater1active"] = ProtoField.bool("xtce.thermalpacket.heater1active", "Heater1Active")
F["thermalpacket.heater2active"] = ProtoField.bool("xtce.thermalpacket.heater2active", "Heater2Active")

local _all_fields = {}
for _, f in pairs(F) do _all_fields[#_all_fields+1] = f end
xtce_proto.fields = _all_fields

-- Container: ADCSPacket (DemoSat/ADCS/ADCSPacket)
local function dissect_adcspacket(buf, pkt, tree)
    tree:set_text("XTCE: ADCSPacket")
    pkt.cols.info = "ADCSPacket"
    if buf:len() >= 1 then tree:add(F["adcspacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["adcspacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["adcspacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["adcspacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["adcspacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["adcspacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["adcspacket.datalength"], buf(4, 2)) end
    if buf:len() >= 10 then tree:add(F["adcspacket.q0"], buf(6, 4)) end
    if buf:len() >= 14 then tree:add(F["adcspacket.q1"], buf(10, 4)) end
    if buf:len() >= 18 then tree:add(F["adcspacket.q2"], buf(14, 4)) end
    if buf:len() >= 22 then tree:add(F["adcspacket.q3"], buf(18, 4)) end
    if buf:len() >= 26 then tree:add(F["adcspacket.omegax"], buf(22, 4)) end
    if buf:len() >= 30 then tree:add(F["adcspacket.omegay"], buf(26, 4)) end
    if buf:len() >= 34 then tree:add(F["adcspacket.omegaz"], buf(30, 4)) end
    if buf:len() >= 38 then tree:add(F["adcspacket.sunangle"], buf(34, 4)) end
    if buf:len() >= 39 then tree:add(F["adcspacket.adcsmode"], buf(38, 1)) end
    if buf:len() >= 40 then tree:add(F["adcspacket.stvalid"], buf(39, 1), buf(39, 1):bitfield(0, 1)) end
    if buf:len() >= 41 then tree:add(F["adcspacket.starcount"], buf(39, 2), buf(39, 2):bitfield(1, 8)) end
end

-- Container: CommPacket (DemoSat/CommPacket)
local function dissect_commpacket(buf, pkt, tree)
    tree:set_text("XTCE: CommPacket")
    pkt.cols.info = "CommPacket"
    if buf:len() >= 1 then tree:add(F["commpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["commpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["commpacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["commpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["commpacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["commpacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["commpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 7 then tree:add(F["commpacket.txpower"], buf(6, 1)) end
    if buf:len() >= 8 then tree:add(F["commpacket.rxsignal"], buf(7, 1)) end
    if buf:len() >= 12 then tree:add(F["commpacket.framessent"], buf(8, 4)) end
    if buf:len() >= 16 then tree:add(F["commpacket.framesreceived"], buf(12, 4)) end
    if buf:len() >= 18 then tree:add(F["commpacket.frameserrored"], buf(16, 2)) end
    if buf:len() >= 19 then tree:add(F["commpacket.linkstate"], buf(18, 1)) end
    if buf:len() >= 23 then tree:add(F["commpacket.symbolrate"], buf(19, 4)) end
end

-- Container: EventPacket (DemoSat/EventPacket)
local function dissect_eventpacket(buf, pkt, tree)
    tree:set_text("XTCE: EventPacket")
    pkt.cols.info = "EventPacket"
    if buf:len() >= 1 then tree:add(F["eventpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["eventpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["eventpacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["eventpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["eventpacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["eventpacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["eventpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 10 then tree:add(F["eventpacket.eventtimestamp"], buf(6, 4)) end
    if buf:len() >= 12 then tree:add(F["eventpacket.eventid"], buf(10, 2)) end
    if buf:len() >= 13 then tree:add(F["eventpacket.eventseverity"], buf(12, 1)) end
    if buf:len() >= 14 then tree:add(F["eventpacket.eventsubsystem"], buf(13, 1)) end
    if buf:len() >= 15 then tree:add(F["eventpacket.eventrepeatcount"], buf(14, 1)) end
    if buf:len() >= 16 then tree:add(F["eventpacket.eventsuppressed"], buf(15, 1)) end
    if buf:len() >= 144 then tree:add(F["eventpacket.eventmessage"], buf(16, 128)) end
end

-- Container: HKPacket (DemoSat/HKPacket)
local function dissect_hkpacket(buf, pkt, tree)
    tree:set_text("XTCE: HKPacket")
    pkt.cols.info = "HKPacket"
    if buf:len() >= 1 then tree:add(F["hkpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["hkpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["hkpacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["hkpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["hkpacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["hkpacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["hkpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 7 then tree:add(F["hkpacket.scmode"], buf(6, 1)) end
    if buf:len() >= 11 then tree:add(F["hkpacket.met"], buf(7, 4)) end
    if buf:len() >= 12 then tree:add(F["hkpacket.resetcause"], buf(11, 1)) end
    if buf:len() >= 14 then tree:add(F["hkpacket.resetcount"], buf(12, 2)) end
    if buf:len() >= 15 then tree:add(F["hkpacket.eclipseflag"], buf(14, 1), buf(14, 1):bitfield(0, 1)) end
    if buf:len() >= 15 then tree:add(F["hkpacket.safemodeflag"], buf(14, 1), buf(14, 1):bitfield(1, 1)) end
    if buf:len() >= 16 then tree:add(F["hkpacket.battsoc"], buf(14, 2), buf(14, 2):bitfield(2, 8)) end
end

-- Container: OBCPacket (DemoSat/OBCPacket)
local function dissect_obcpacket(buf, pkt, tree)
    tree:set_text("XTCE: OBCPacket")
    pkt.cols.info = "OBCPacket"
    if buf:len() >= 1 then tree:add(F["obcpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["obcpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["obcpacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["obcpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["obcpacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["obcpacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["obcpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 7 then tree:add(F["obcpacket.cpuload1s"], buf(6, 1)) end
    if buf:len() >= 8 then tree:add(F["obcpacket.cpuload5s"], buf(7, 1)) end
    if buf:len() >= 9 then tree:add(F["obcpacket.cpuload15s"], buf(8, 1)) end
    if buf:len() >= 13 then tree:add(F["obcpacket.memfreekb"], buf(9, 4)) end
    if buf:len() >= 15 then tree:add(F["obcpacket.flasherrors"], buf(13, 2)) end
    if buf:len() >= 17 then tree:add(F["obcpacket.coretemp"], buf(15, 2)) end
end

-- Container: CalPacket (DemoSat/Payload/CalPacket)
local function dissect_calpacket(buf, pkt, tree)
    tree:set_text("XTCE: CalPacket")
    pkt.cols.info = "CalPacket"
    if buf:len() >= 1 then tree:add(F["calpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["calpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["calpacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["calpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["calpacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["calpacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["calpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 7 then tree:add(F["calpacket.calstate"], buf(6, 1)) end
    if buf:len() >= 8 then tree:add(F["calpacket.calprogress"], buf(7, 1)) end
    if buf:len() >= 9 then tree:add(F["calpacket.caltargetch"], buf(8, 1)) end
    if buf:len() >= 17 then tree:add(F["calpacket.calreference"], buf(9, 8)) end
    if buf:len() >= 25 then tree:add(F["calpacket.caldark"], buf(17, 8)) end
end

-- Container: SciPacket (DemoSat/Payload/SciPacket)
local function dissect_scipacket(buf, pkt, tree)
    tree:set_text("XTCE: SciPacket")
    pkt.cols.info = "SciPacket"
    if buf:len() >= 1 then tree:add(F["scipacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["scipacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["scipacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["scipacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["scipacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["scipacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["scipacket.datalength"], buf(4, 2)) end
    if buf:len() >= 10 then tree:add(F["scipacket.scitimestamp"], buf(6, 4)) end
    if buf:len() >= 14 then tree:add(F["scipacket.integtime"], buf(10, 4)) end
    if buf:len() >= 18 then tree:add(F["scipacket.ch1counts"], buf(14, 4)) end
    if buf:len() >= 22 then tree:add(F["scipacket.ch2counts"], buf(18, 4)) end
    if buf:len() >= 26 then tree:add(F["scipacket.ch3counts"], buf(22, 4)) end
    if buf:len() >= 30 then tree:add(F["scipacket.ch4counts"], buf(26, 4)) end
    if buf:len() >= 32 then tree:add(F["scipacket.ccdtemp"], buf(30, 2)) end
    if buf:len() >= 36 then tree:add(F["scipacket.darkcurrent"], buf(32, 4)) end
    if buf:len() >= 40 then tree:add(F["scipacket.scichecksum"], buf(36, 4)) end
end

-- Container: PowerPacket (DemoSat/PowerPacket)
local function dissect_powerpacket(buf, pkt, tree)
    tree:set_text("XTCE: PowerPacket")
    pkt.cols.info = "PowerPacket"
    if buf:len() >= 1 then tree:add(F["powerpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["powerpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["powerpacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["powerpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["powerpacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["powerpacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["powerpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 8 then tree:add(F["powerpacket.battvoltage"], buf(6, 2)) end
    if buf:len() >= 10 then tree:add(F["powerpacket.battcurrent"], buf(8, 2)) end
    if buf:len() >= 12 then tree:add(F["powerpacket.solarvoltage"], buf(10, 2)) end
    if buf:len() >= 14 then tree:add(F["powerpacket.solarcurrent"], buf(12, 2)) end
    if buf:len() >= 15 then tree:add(F["powerpacket.battsoc"], buf(14, 1)) end
    if buf:len() >= 17 then tree:add(F["powerpacket.batttemp"], buf(15, 2)) end
    if buf:len() >= 18 then tree:add(F["powerpacket.powermode"], buf(17, 1)) end
    if buf:len() >= 22 then tree:add(F["powerpacket.loadpower"], buf(18, 4)) end
    if buf:len() >= 26 then tree:add(F["powerpacket.chargepower"], buf(22, 4)) end
end

-- Container: ThermalPacket (DemoSat/ThermalPacket)
local function dissect_thermalpacket(buf, pkt, tree)
    tree:set_text("XTCE: ThermalPacket")
    pkt.cols.info = "ThermalPacket"
    if buf:len() >= 1 then tree:add(F["thermalpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["thermalpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["thermalpacket.sechdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["thermalpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["thermalpacket.seqflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["thermalpacket.seqcount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["thermalpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 8 then tree:add(F["thermalpacket.temppcb"], buf(6, 2)) end
    if buf:len() >= 10 then tree:add(F["thermalpacket.tempbattery"], buf(8, 2)) end
    if buf:len() >= 12 then tree:add(F["thermalpacket.tempsolararray1"], buf(10, 2)) end
    if buf:len() >= 14 then tree:add(F["thermalpacket.tempsolararray2"], buf(12, 2)) end
    if buf:len() >= 15 then tree:add(F["thermalpacket.heater1active"], buf(14, 1), buf(14, 1):bitfield(0, 1)) end
    if buf:len() >= 15 then tree:add(F["thermalpacket.heater2active"], buf(14, 1), buf(14, 1):bitfield(1, 1)) end
end

-- Discriminator dispatch map
local XTCE_MAP = {
    [200] = dissect_adcspacket,
    [130] = dissect_commpacket,
    [150] = dissect_eventpacket,
    [100] = dissect_hkpacket,
    [140] = dissect_obcpacket,
    [301] = dissect_calpacket,
    [300] = dissect_scipacket,
    [110] = dissect_powerpacket,
    [120] = dissect_thermalpacket,
}

-- Main dissect function
function xtce_proto.dissector(buf, pkt, tree)
    pkt.cols.protocol = "XTCE"
    local subtree = tree:add(xtce_proto, buf(), "XTCE Telemetry")
    if buf:len() < 2 then return end
    local disc_val = buf(0, 2):bitfield(5, 11)
    local fn = XTCE_MAP[disc_val]
    if fn then fn(buf, pkt, subtree)
    else subtree:add("Unknown packet type: " .. disc_val) end
end

local PORT = 4321
local udp_table = DissectorTable.get("udp.port")
udp_table:add(PORT, xtce_proto)
