-- Auto-generated XTCE Wireshark Lua dissector
-- Generated by xtce-tools gen-dissector

local xtce_proto = Proto("xtce", "XTCE Telemetry")

-- ProtoField declarations
local F = {}
F["diagpacket.versionnumber"] = ProtoField.uint8("xtce.diagpacket.versionnumber", "VersionNumber", base.DEC)
F["diagpacket.packettype"] = ProtoField.uint8("xtce.diagpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["diagpacket.secondaryhdrflag"] = ProtoField.bool("xtce.diagpacket.secondaryhdrflag", "SecondaryHdrFlag")
F["diagpacket.apid"] = ProtoField.uint16("xtce.diagpacket.apid", "APID", base.DEC)
F["diagpacket.sequenceflags"] = ProtoField.uint8("xtce.diagpacket.sequenceflags", "SequenceFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["diagpacket.sequencecount"] = ProtoField.uint16("xtce.diagpacket.sequencecount", "SequenceCount", base.DEC)
F["diagpacket.datalength"] = ProtoField.uint16("xtce.diagpacket.datalength", "DataLength", base.DEC)
F["diagpacket.diagvoltagele"] = ProtoField.uint16("xtce.diagpacket.diagvoltagele", "DiagVoltageLE", base.DEC)
F["diagpacket.diagtemple"] = ProtoField.int16("xtce.diagpacket.diagtemple", "DiagTempLE", base.DEC)
F["diagpacket.diagcounterle"] = ProtoField.uint32("xtce.diagpacket.diagcounterle", "DiagCounterLE", base.DEC)
F["diagpacket.diagstatus"] = ProtoField.uint8("xtce.diagpacket.diagstatus", "DiagStatus", base.DEC)
F["diagpacket.diagblob"] = ProtoField.bytes("xtce.diagpacket.diagblob", "DiagBlob")
F["eventpacket.versionnumber"] = ProtoField.uint8("xtce.eventpacket.versionnumber", "VersionNumber", base.DEC)
F["eventpacket.packettype"] = ProtoField.uint8("xtce.eventpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["eventpacket.secondaryhdrflag"] = ProtoField.bool("xtce.eventpacket.secondaryhdrflag", "SecondaryHdrFlag")
F["eventpacket.apid"] = ProtoField.uint16("xtce.eventpacket.apid", "APID", base.DEC)
F["eventpacket.sequenceflags"] = ProtoField.uint8("xtce.eventpacket.sequenceflags", "SequenceFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["eventpacket.sequencecount"] = ProtoField.uint16("xtce.eventpacket.sequencecount", "SequenceCount", base.DEC)
F["eventpacket.datalength"] = ProtoField.uint16("xtce.eventpacket.datalength", "DataLength", base.DEC)
F["eventpacket.evtimestamp"] = ProtoField.bytes("xtce.eventpacket.evtimestamp", "EvTimestamp")
F["eventpacket.eventid"] = ProtoField.uint16("xtce.eventpacket.eventid", "EventId", base.DEC)
F["eventpacket.eventseverity"] = ProtoField.uint8("xtce.eventpacket.eventseverity", "EventSeverity", base.DEC, {[0]="DEBUG", [1]="INFO", [2]="WARNING", [3]="ERROR", [4]="CRITICAL"})
F["eventpacket.eventmsg"] = ProtoField.string("xtce.eventpacket.eventmsg", "EventMsg")
F["hkpacket.versionnumber"] = ProtoField.uint8("xtce.hkpacket.versionnumber", "VersionNumber", base.DEC)
F["hkpacket.packettype"] = ProtoField.uint8("xtce.hkpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["hkpacket.secondaryhdrflag"] = ProtoField.bool("xtce.hkpacket.secondaryhdrflag", "SecondaryHdrFlag")
F["hkpacket.apid"] = ProtoField.uint16("xtce.hkpacket.apid", "APID", base.DEC)
F["hkpacket.sequenceflags"] = ProtoField.uint8("xtce.hkpacket.sequenceflags", "SequenceFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["hkpacket.sequencecount"] = ProtoField.uint16("xtce.hkpacket.sequencecount", "SequenceCount", base.DEC)
F["hkpacket.datalength"] = ProtoField.uint16("xtce.hkpacket.datalength", "DataLength", base.DEC)
F["hkpacket.scmode"] = ProtoField.uint8("xtce.hkpacket.scmode", "SCMode", base.DEC, {[0]="STANDBY", [1]="NOMINAL", [2]="SCIENCE", [3]="ECLIPSE", [4]="SAFE", [5]="CONTINGENCY"})
F["hkpacket.uptime"] = ProtoField.uint32("xtce.hkpacket.uptime", "Uptime", base.DEC)
F["hkpacket.battvoltage"] = ProtoField.uint16("xtce.hkpacket.battvoltage", "BattVoltage", base.DEC)
F["hkpacket.battcurrent"] = ProtoField.uint16("xtce.hkpacket.battcurrent", "BattCurrent", base.DEC)
F["hkpacket.battsoc"] = ProtoField.uint8("xtce.hkpacket.battsoc", "BattSOC", base.DEC)
F["hkpacket.cpuload"] = ProtoField.uint8("xtce.hkpacket.cpuload", "CpuLoad", base.DEC)
F["hkpacket.coretempraw"] = ProtoField.uint16("xtce.hkpacket.coretempraw", "CoreTempRaw", base.DEC)
F["hkpacket.resetcount"] = ProtoField.uint8("xtce.hkpacket.resetcount", "ResetCount", base.DEC)
F["hkpacket.eclipseflag"] = ProtoField.bool("xtce.hkpacket.eclipseflag", "EclipseFlag")
F["hkpacket.faultflags"] = ProtoField.uint16("xtce.hkpacket.faultflags", "FaultFlags", base.DEC)
F["scipacket.versionnumber"] = ProtoField.uint8("xtce.scipacket.versionnumber", "VersionNumber", base.DEC)
F["scipacket.packettype"] = ProtoField.uint8("xtce.scipacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["scipacket.secondaryhdrflag"] = ProtoField.bool("xtce.scipacket.secondaryhdrflag", "SecondaryHdrFlag")
F["scipacket.apid"] = ProtoField.uint16("xtce.scipacket.apid", "APID", base.DEC)
F["scipacket.sequenceflags"] = ProtoField.uint8("xtce.scipacket.sequenceflags", "SequenceFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["scipacket.sequencecount"] = ProtoField.uint16("xtce.scipacket.sequencecount", "SequenceCount", base.DEC)
F["scipacket.datalength"] = ProtoField.uint16("xtce.scipacket.datalength", "DataLength", base.DEC)
F["scipacket.scitimestamp"] = ProtoField.bytes("xtce.scipacket.scitimestamp", "SciTimestamp")
F["scipacket.integtimeus"] = ProtoField.uint32("xtce.scipacket.integtimeus", "IntegTimeUs", base.DEC)
F["scipacket.ch1counts"] = ProtoField.uint32("xtce.scipacket.ch1counts", "Ch1Counts", base.DEC)
F["scipacket.ch2counts"] = ProtoField.uint32("xtce.scipacket.ch2counts", "Ch2Counts", base.DEC)
F["scipacket.calibratedflux"] = ProtoField.double("xtce.scipacket.calibratedflux", "CalibratedFlux")
F["scipacket.readouttemp"] = ProtoField.float("xtce.scipacket.readouttemp", "ReadoutTemp")
F["scipacket.frameserial"] = ProtoField.int32("xtce.scipacket.frameserial", "FrameSerial", base.DEC)
F["statuspacket.versionnumber"] = ProtoField.uint8("xtce.statuspacket.versionnumber", "VersionNumber", base.DEC)
F["statuspacket.packettype"] = ProtoField.uint8("xtce.statuspacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["statuspacket.secondaryhdrflag"] = ProtoField.bool("xtce.statuspacket.secondaryhdrflag", "SecondaryHdrFlag")
F["statuspacket.apid"] = ProtoField.uint16("xtce.statuspacket.apid", "APID", base.DEC)
F["statuspacket.sequenceflags"] = ProtoField.uint8("xtce.statuspacket.sequenceflags", "SequenceFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["statuspacket.sequencecount"] = ProtoField.uint16("xtce.statuspacket.sequencecount", "SequenceCount", base.DEC)
F["statuspacket.datalength"] = ProtoField.uint16("xtce.statuspacket.datalength", "DataLength", base.DEC)
F["statuspacket.spacecraftmode"] = ProtoField.uint8("xtce.statuspacket.spacecraftmode", "SpacecraftMode", base.DEC, {[0]="STANDBY", [1]="NOMINAL", [2]="SCIENCE", [3]="ECLIPSE", [4]="SAFE", [5]="CONTINGENCY"})
F["statuspacket.powermode"] = ProtoField.uint8("xtce.statuspacket.powermode", "PowerMode", base.DEC, {[0]="CHARGING", [1]="DISCHARGING", [2]="BALANCED", [3]="FAULT"})
F["statuspacket.linkstate"] = ProtoField.uint8("xtce.statuspacket.linkstate", "LinkState", base.DEC, {[0]="IDLE", [1]="ACQUISITION", [2]="TRACKING", [3]="LOCKED", [4]="LOST"})
F["statuspacket.payloadactive"] = ProtoField.bool("xtce.statuspacket.payloadactive", "PayloadActive")
F["statuspacket.lastcmdid"] = ProtoField.uint16("xtce.statuspacket.lastcmdid", "LastCmdId", base.DEC)
F["statuspacket.uptimesec"] = ProtoField.uint32("xtce.statuspacket.uptimesec", "UptimeSec", base.DEC)
F["timesyncpacket.versionnumber"] = ProtoField.uint8("xtce.timesyncpacket.versionnumber", "VersionNumber", base.DEC)
F["timesyncpacket.packettype"] = ProtoField.uint8("xtce.timesyncpacket.packettype", "PacketType", base.DEC, {[0]="TM", [1]="TC"})
F["timesyncpacket.secondaryhdrflag"] = ProtoField.bool("xtce.timesyncpacket.secondaryhdrflag", "SecondaryHdrFlag")
F["timesyncpacket.apid"] = ProtoField.uint16("xtce.timesyncpacket.apid", "APID", base.DEC)
F["timesyncpacket.sequenceflags"] = ProtoField.uint8("xtce.timesyncpacket.sequenceflags", "SequenceFlags", base.DEC, {[0]="CONTINUATION", [1]="FIRST", [2]="LAST", [3]="STANDALONE"})
F["timesyncpacket.sequencecount"] = ProtoField.uint16("xtce.timesyncpacket.sequencecount", "SequenceCount", base.DEC)
F["timesyncpacket.datalength"] = ProtoField.uint16("xtce.timesyncpacket.datalength", "DataLength", base.DEC)
F["timesyncpacket.gpsseconds"] = ProtoField.uint64("xtce.timesyncpacket.gpsseconds", "GPSSeconds", base.DEC)
F["timesyncpacket.subsecondsns"] = ProtoField.uint32("xtce.timesyncpacket.subsecondsns", "SubsecondsNs", base.DEC)
F["timesyncpacket.syncsource"] = ProtoField.uint8("xtce.timesyncpacket.syncsource", "SyncSource", base.DEC, {[0]="INTERNAL", [1]="GPS", [2]="UPLINK", [3]="GNSS"})
F["timesyncpacket.timingvalid"] = ProtoField.bool("xtce.timesyncpacket.timingvalid", "TimingValid")

local _all_fields = {}
for _, f in pairs(F) do _all_fields[#_all_fields+1] = f end
xtce_proto.fields = _all_fields

-- Container: DiagPacket (CCSDSRealWorld/DiagPacket)
local function dissect_diagpacket(buf, pkt, tree)
    if buf:len() >= 1 then tree:add(F["diagpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["diagpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["diagpacket.secondaryhdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["diagpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["diagpacket.sequenceflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["diagpacket.sequencecount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["diagpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 8 then tree:add_le(F["diagpacket.diagvoltagele"], buf(6, 2)) end
    if buf:len() >= 10 then tree:add_le(F["diagpacket.diagtemple"], buf(8, 2)) end
    if buf:len() >= 14 then tree:add_le(F["diagpacket.diagcounterle"], buf(10, 4)) end
    if buf:len() >= 15 then tree:add(F["diagpacket.diagstatus"], buf(14, 1)) end
    if buf:len() >= 31 then tree:add(F["diagpacket.diagblob"], buf(15, 16)) end
end

-- Container: EventPacket (CCSDSRealWorld/EventPacket)
local function dissect_eventpacket(buf, pkt, tree)
    if buf:len() >= 1 then tree:add(F["eventpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["eventpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["eventpacket.secondaryhdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["eventpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["eventpacket.sequenceflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["eventpacket.sequencecount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["eventpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 10 then tree:add(F["eventpacket.evtimestamp"], buf(6, 4)) end
    if buf:len() >= 12 then tree:add(F["eventpacket.eventid"], buf(10, 2)) end
    if buf:len() >= 13 then tree:add(F["eventpacket.eventseverity"], buf(12, 1)) end
    if buf:len() >= 93 then tree:add(F["eventpacket.eventmsg"], buf(13, 80)) end
end

-- Container: HKPacket (CCSDSRealWorld/HKPacket)
local function dissect_hkpacket(buf, pkt, tree)
    if buf:len() >= 1 then tree:add(F["hkpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["hkpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["hkpacket.secondaryhdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["hkpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["hkpacket.sequenceflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["hkpacket.sequencecount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["hkpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 7 then tree:add(F["hkpacket.scmode"], buf(6, 1)) end
    if buf:len() >= 11 then tree:add(F["hkpacket.uptime"], buf(7, 4)) end
    if buf:len() >= 13 then tree:add(F["hkpacket.battvoltage"], buf(11, 2)) end
    if buf:len() >= 15 then tree:add(F["hkpacket.battcurrent"], buf(13, 2)) end
    if buf:len() >= 16 then tree:add(F["hkpacket.battsoc"], buf(15, 1)) end
    if buf:len() >= 17 then tree:add(F["hkpacket.cpuload"], buf(16, 1)) end
    if buf:len() >= 19 then tree:add(F["hkpacket.coretempraw"], buf(17, 2)) end
    if buf:len() >= 20 then tree:add(F["hkpacket.resetcount"], buf(19, 1)) end
    if buf:len() >= 21 then tree:add(F["hkpacket.eclipseflag"], buf(20, 1)) end
    if buf:len() >= 23 then tree:add(F["hkpacket.faultflags"], buf(21, 2)) end
end

-- Container: SciPacket (CCSDSRealWorld/SciPacket)
local function dissect_scipacket(buf, pkt, tree)
    if buf:len() >= 1 then tree:add(F["scipacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["scipacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["scipacket.secondaryhdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["scipacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["scipacket.sequenceflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["scipacket.sequencecount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["scipacket.datalength"], buf(4, 2)) end
    if buf:len() >= 10 then tree:add(F["scipacket.scitimestamp"], buf(6, 4)) end
    if buf:len() >= 14 then tree:add(F["scipacket.integtimeus"], buf(10, 4)) end
    if buf:len() >= 18 then tree:add(F["scipacket.ch1counts"], buf(14, 4)) end
    if buf:len() >= 22 then tree:add(F["scipacket.ch2counts"], buf(18, 4)) end
    if buf:len() >= 30 then tree:add(F["scipacket.calibratedflux"], buf(22, 8)) end
    if buf:len() >= 34 then tree:add(F["scipacket.readouttemp"], buf(30, 4)) end
    if buf:len() >= 38 then tree:add(F["scipacket.frameserial"], buf(34, 4)) end
end

-- Container: StatusPacket (CCSDSRealWorld/StatusPacket)
local function dissect_statuspacket(buf, pkt, tree)
    if buf:len() >= 1 then tree:add(F["statuspacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["statuspacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["statuspacket.secondaryhdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["statuspacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["statuspacket.sequenceflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["statuspacket.sequencecount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["statuspacket.datalength"], buf(4, 2)) end
    if buf:len() >= 7 then tree:add(F["statuspacket.spacecraftmode"], buf(6, 1)) end
    if buf:len() >= 8 then tree:add(F["statuspacket.powermode"], buf(7, 1)) end
    if buf:len() >= 9 then tree:add(F["statuspacket.linkstate"], buf(8, 1)) end
    if buf:len() >= 10 then tree:add(F["statuspacket.payloadactive"], buf(9, 1)) end
    if buf:len() >= 12 then tree:add(F["statuspacket.lastcmdid"], buf(10, 2)) end
    if buf:len() >= 16 then tree:add(F["statuspacket.uptimesec"], buf(12, 4)) end
end

-- Container: TimeSyncPacket (CCSDSRealWorld/TimeSyncPacket)
local function dissect_timesyncpacket(buf, pkt, tree)
    if buf:len() >= 1 then tree:add(F["timesyncpacket.versionnumber"], buf(0, 1), buf(0, 1):bitfield(0, 3)) end
    if buf:len() >= 1 then tree:add(F["timesyncpacket.packettype"], buf(0, 1), buf(0, 1):bitfield(3, 1)) end
    if buf:len() >= 1 then tree:add(F["timesyncpacket.secondaryhdrflag"], buf(0, 1), buf(0, 1):bitfield(4, 1)) end
    if buf:len() >= 2 then tree:add(F["timesyncpacket.apid"], buf(0, 2), buf(0, 2):bitfield(5, 11)) end
    if buf:len() >= 3 then tree:add(F["timesyncpacket.sequenceflags"], buf(2, 1), buf(2, 1):bitfield(0, 2)) end
    if buf:len() >= 4 then tree:add(F["timesyncpacket.sequencecount"], buf(2, 2), buf(2, 2):bitfield(2, 14)) end
    if buf:len() >= 6 then tree:add(F["timesyncpacket.datalength"], buf(4, 2)) end
    if buf:len() >= 14 then tree:add(F["timesyncpacket.gpsseconds"], buf(6, 8)) end
    if buf:len() >= 18 then tree:add(F["timesyncpacket.subsecondsns"], buf(14, 4)) end
    if buf:len() >= 19 then tree:add(F["timesyncpacket.syncsource"], buf(18, 1)) end
    if buf:len() >= 20 then tree:add(F["timesyncpacket.timingvalid"], buf(19, 1)) end
end

-- Discriminator dispatch map
local XTCE_MAP = {
    [400] = dissect_diagpacket,
    [300] = dissect_eventpacket,
    [100] = dissect_hkpacket,
    [200] = dissect_scipacket,
    [600] = dissect_statuspacket,
    [500] = dissect_timesyncpacket,
}

-- Main dissect function
function xtce_proto.dissector(buf, pkt, tree)
    pkt.cols.protocol = "XTCE"
    local subtree = tree:add(xtce_proto, buf(), "XTCE Telemetry")
    if buf:len() < 2 then return end
    local disc_val = buf(0, 2):bitfield(5, 11)
    local fn = XTCE_MAP[disc_val]
    if fn then fn(buf, pkt, subtree)
    else subtree:add("Unknown packet type: " .. disc_val) end
end

local PORT = 4321
local udp_table = DissectorTable.get("udp.port")
udp_table:add(PORT, xtce_proto)
