-- Auto-generated XTCE Wireshark Lua dissector
-- Generated by xtce-tools gen-dissector

local xtce_proto = Proto("xtce", "XTCE Telemetry")

-- ProtoField declarations
local F = {}
F["systemstatuspacket.apid"] = ProtoField.uint16("xtce.systemstatuspacket.apid", "APID", base.DEC)
F["systemstatuspacket.satellitestate"] = ProtoField.uint8("xtce.systemstatuspacket.satellitestate", "SatelliteState", base.DEC, {[0]="BOOT", [1]="NOMINAL", [2]="SAFE_MODE"})
F["systemstatuspacket.lasteventmsg"] = ProtoField.string("xtce.systemstatuspacket.lasteventmsg", "LastEventMsg")

local _all_fields = {}
for _, f in pairs(F) do _all_fields[#_all_fields+1] = f end
xtce_proto.fields = _all_fields

-- Container: SystemStatusPacket (AdvancedSat/SystemStatusPacket)
local function dissect_systemstatuspacket(buf, pkt, tree)
    if buf:len() >= 2 then tree:add(F["systemstatuspacket.apid"], buf(0, 2), buf(0, 2):bitfield(0, 11)) end
    if buf:len() >= 2 then tree:add(F["systemstatuspacket.satellitestate"], buf(1, 1), buf(1, 1):bitfield(3, 2)) end
    if buf:len() >= 2 then tree:add(F["systemstatuspacket.lasteventmsg"], buf(1, 1), buf(1, 1):bitfield(5, 0)) end
end

-- Discriminator dispatch map
local XTCE_MAP = {
    [104] = dissect_systemstatuspacket,
}

-- Main dissect function
function xtce_proto.dissector(buf, pkt, tree)
    pkt.cols.protocol = "XTCE"
    local subtree = tree:add(xtce_proto, buf(), "XTCE Telemetry")
    if buf:len() < 2 then return end
    local disc_val = buf(0, 2):bitfield(0, 11)
    local fn = XTCE_MAP[disc_val]
    if fn then fn(buf, pkt, subtree)
    else subtree:add("Unknown packet type: " .. disc_val) end
end

local PORT = 4321
local udp_table = DissectorTable.get("udp.port")
udp_table:add(PORT, xtce_proto)
